# Supported: GCC, CLANG, ICC, NVCC
TAG ?= ICX
ENABLE_OPENMP ?= false

#Feature options
OPTIONS +=  -DARRAY_ALIGNMENT=64
#OPTIONS +=  -DVERBOSE_AFFINITY
#OPTIONS +=  -DVERBOSE_DATASIZE
#OPTIONS +=  -DVERBOSE_TIMER
